# [GM] BEGIN streamlit theme
[theme]
base = "light"
# [GM] END streamlit theme

[client]
# Configuration minimale de la toolbar
toolbarMode = "minimal"
showErrorDetails = false

[runner]
# Optimisations de performance
magicEnabled = true

[server]
# Configuration serveur
headless = true
runOnSave = true
maxUploadSize = 10
enableXsrfProtection = true