# GuignoMap - Échantillon des secrets pour Streamlit Cloud
# 
# Instructions:
# 1. Copiez le contenu de ce fichier
# 2. Collez dans "App secrets" de votre app Streamlit Cloud
# 3. Adaptez les valeurs selon votre environnement

# ====================================================================
# MODE D'EXÉCUTION
# ====================================================================
# "demo"   = Mode démonstration (fallback intelligent vers DB sample)
# "client" = Mode production (exige guigno_map.db principal)
MODE = "demo"

# ====================================================================
# AUTHENTIFICATION
# ====================================================================
# Permet le fallback bcrypt pour compatibilité anciennes installations
ALLOW_BCRYPT_FALLBACK = true

# ====================================================================
# CONFIGURATION OPTIONNELLE STREAMLIT CLOUD
# ====================================================================
# Désactive les logs de debug pour améliorer les performances
# [logger]
# level = "WARNING"

# Force l'encodage UTF-8 pour éviter les problèmes de caractères
# PYTHONUTF8 = "1"

# ====================================================================
# NOTES DE DÉPLOIEMENT
# ====================================================================
# - Le mode "demo" est recommandé pour Streamlit Cloud
# - Les fichiers uploadés ne sont pas persistants sur Cloud
# - Utilisez les boutons de téléchargement pour sauvegarder les exports
# - La base de données est créée automatiquement en mode demo